### ISSUE TITLE
Switch Socket singleton to be created based off connection with quote server

### ISSUE THREAD

**Issue by Fattouche** [Fattouche/DayTrader#19]
Since the quote server uses socket communication, we should try to keep sockets open for as long as possible(I'm not sure if they close on their end, we will need to figure this out). Either way, the current setup creates a singleton socket which isn't exactly what we want. We want it to be able to determine whether or not the connection with the quote server is lost and only then attempt to establish a new connection.

**Comment by gurjy0t** [comment]
I think we could use a similar keep-alive idea to keep a connection always alive to the quote server, and auto open one if the server closes it. Could have a single thread responsible for handling that. What u think
