### ISSUE TITLE
What is this doing?

### ISSUE THREAD

**Issue by IsaacSahle** [Fattouche/DayTrader#37]
https://github.com/Fattouche/DayTrader/blob/4e43d573a34235cfffaf0c67a53cc5657d4d63da/python/day_trader/exchange/models/business_models.py#L155

**Comment by IsaacSahle** [comment]
We never use a

**Comment by Fattouche** [comment]
Yea I have no idea lol

**Comment by Fattouche** [comment]
We were pretty tired when we thought of the logic for that stuff
